
package com.training.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalcImpl", targetNamespace = "http://service.training.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalcImpl {


    /**
     * 
     * @param x
     * @param y
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "addReturn", targetNamespace = "http://service.training.com")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.training.com", className = "com.training.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.training.com", className = "com.training.service.AddResponse")
    public double add(
        @WebParam(name = "x", targetNamespace = "http://service.training.com")
        int x,
        @WebParam(name = "y", targetNamespace = "http://service.training.com")
        int y);

}
