
package com.training.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalcService", targetNamespace = "http://service.training.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalcService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.training.com/", className = "com.training.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.training.com/", className = "com.training.service.AddResponse")
    @Action(input = "http://service.training.com/CalcService/addRequest", output = "http://service.training.com/CalcService/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://service.training.com/", className = "com.training.service.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://service.training.com/", className = "com.training.service.SubResponse")
    @Action(input = "http://service.training.com/CalcService/subRequest", output = "http://service.training.com/CalcService/subResponse")
    public int sub(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "div", targetNamespace = "http://service.training.com/", className = "com.training.service.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://service.training.com/", className = "com.training.service.DivResponse")
    @Action(input = "http://service.training.com/CalcService/divRequest", output = "http://service.training.com/CalcService/divResponse")
    public int div(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mul", targetNamespace = "http://service.training.com/", className = "com.training.service.Mul")
    @ResponseWrapper(localName = "mulResponse", targetNamespace = "http://service.training.com/", className = "com.training.service.MulResponse")
    @Action(input = "http://service.training.com/CalcService/mulRequest", output = "http://service.training.com/CalcService/mulResponse")
    public int mul(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
