
package com.ameex.training.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.ameex.training.business.Product;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductServiceImpl", targetNamespace = "http://service.training.ameex.com")
@XmlSeeAlso({
    com.ameex.training.business.ObjectFactory.class,
    com.ameex.training.service.ObjectFactory.class
})
public interface ProductServiceImpl {


    /**
     * 
     * @param product
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "addProductReturn", targetNamespace = "http://service.training.ameex.com")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://service.training.ameex.com", className = "com.ameex.training.service.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://service.training.ameex.com", className = "com.ameex.training.service.AddProductResponse")
    public boolean addProduct(
        @WebParam(name = "product", targetNamespace = "http://service.training.ameex.com")
        Product product);

    /**
     * 
     * @param product
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "deleteProductReturn", targetNamespace = "http://service.training.ameex.com")
    @RequestWrapper(localName = "deleteProduct", targetNamespace = "http://service.training.ameex.com", className = "com.ameex.training.service.DeleteProduct")
    @ResponseWrapper(localName = "deleteProductResponse", targetNamespace = "http://service.training.ameex.com", className = "com.ameex.training.service.DeleteProductResponse")
    public boolean deleteProduct(
        @WebParam(name = "product", targetNamespace = "http://service.training.ameex.com")
        Product product);

    /**
     * 
     * @param id
     * @return
     *     returns com.ameex.training.business.Product
     */
    @WebMethod
    @WebResult(name = "findProductReturn", targetNamespace = "http://service.training.ameex.com")
    @RequestWrapper(localName = "findProduct", targetNamespace = "http://service.training.ameex.com", className = "com.ameex.training.service.FindProduct")
    @ResponseWrapper(localName = "findProductResponse", targetNamespace = "http://service.training.ameex.com", className = "com.ameex.training.service.FindProductResponse")
    public Product findProduct(
        @WebParam(name = "id", targetNamespace = "http://service.training.ameex.com")
        int id);

    /**
     * 
     * @param product
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "updateProductReturn", targetNamespace = "http://service.training.ameex.com")
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://service.training.ameex.com", className = "com.ameex.training.service.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://service.training.ameex.com", className = "com.ameex.training.service.UpdateProductResponse")
    public boolean updateProduct(
        @WebParam(name = "product", targetNamespace = "http://service.training.ameex.com")
        Product product);

}
