
package com.training.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankServiceImpl", targetNamespace = "http://service.training.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankServiceImpl {


    /**
     * 
     * @param ch
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "getLoanInterestRateReturn", targetNamespace = "http://service.training.com")
    @RequestWrapper(localName = "getLoanInterestRate", targetNamespace = "http://service.training.com", className = "com.training.service.GetLoanInterestRate")
    @ResponseWrapper(localName = "getLoanInterestRateResponse", targetNamespace = "http://service.training.com", className = "com.training.service.GetLoanInterestRateResponse")
    public double getLoanInterestRate(
        @WebParam(name = "ch", targetNamespace = "http://service.training.com")
        Object ch);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sayHelloReturn", targetNamespace = "http://service.training.com")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.training.com", className = "com.training.service.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.training.com", className = "com.training.service.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "http://service.training.com")
        String name);

    /**
     * 
     * @param x
     * @param y
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "getSumReturn", targetNamespace = "http://service.training.com")
    @RequestWrapper(localName = "getSum", targetNamespace = "http://service.training.com", className = "com.training.service.GetSum")
    @ResponseWrapper(localName = "getSumResponse", targetNamespace = "http://service.training.com", className = "com.training.service.GetSumResponse")
    public int getSum(
        @WebParam(name = "x", targetNamespace = "http://service.training.com")
        int x,
        @WebParam(name = "y", targetNamespace = "http://service.training.com")
        int y);

}
