
package com.training.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CollegeService", targetNamespace = "http://service.training.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CollegeService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCollegePhone", targetNamespace = "http://service.training.com/", className = "com.training.service.GetCollegePhone")
    @ResponseWrapper(localName = "getCollegePhoneResponse", targetNamespace = "http://service.training.com/", className = "com.training.service.GetCollegePhoneResponse")
    @Action(input = "http://service.training.com/CollegeService/getCollegePhoneRequest", output = "http://service.training.com/CollegeService/getCollegePhoneResponse")
    public String getCollegePhone();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCollegeName", targetNamespace = "http://service.training.com/", className = "com.training.service.GetCollegeName")
    @ResponseWrapper(localName = "getCollegeNameResponse", targetNamespace = "http://service.training.com/", className = "com.training.service.GetCollegeNameResponse")
    @Action(input = "http://service.training.com/CollegeService/getCollegeNameRequest", output = "http://service.training.com/CollegeService/getCollegeNameResponse")
    public String getCollegeName();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCollegeEmail", targetNamespace = "http://service.training.com/", className = "com.training.service.GetCollegeEmail")
    @ResponseWrapper(localName = "getCollegeEmailResponse", targetNamespace = "http://service.training.com/", className = "com.training.service.GetCollegeEmailResponse")
    @Action(input = "http://service.training.com/CollegeService/getCollegeEmailRequest", output = "http://service.training.com/CollegeService/getCollegeEmailResponse")
    public String getCollegeEmail();

}
